options:
  iface:
    type: string
    default: ""
    description: |
      The interface to bind flannel overlay networking. The default value is
      the interface bound to the cni endpoint.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to Flannel
  port:
    type: int
    default: 0
    description: |
      Network port to use for Flannel
  vni:
    type: int
    default: 0
    description: |
      VXLAN network id to assign to Flannel
  subnet-len:
    type: int
    default: 24
    description: |
      The size of the subnet allocated to each host.
